IDesastre/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from login import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cidade/', include('cidades.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^especialista/', include('cadastro_especialistas.urls')),
    url(r'^abrigo/', include('cadastro_abrigos.urls')),
    url(r'^', include('home.urls')),
]

cadastro_especialistas/urls.py
from django.conf.urls import url
from . import views

app_name = 'especialistas'

urlpatterns = [
	url(r'^$', views.main, name='main'),
	url(r'^cadastro/$', views.cadastro, name='cadastro'),
	url(r'^indice/$', views.indice, name='indice'),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
	url(r'^$', views.index, name='home'),
]

cadastro_especialistas/models.py
from django.db import models
from django.contrib.auth.models import User

class Especialista(models.Model):
	nome = models.CharField(max_length=50)
	especialidade = models.CharField(max_length=100)
	usuario = models.OneToOneField(User)

cadastro_especialistas/forms.py
from django import forms
from cadastro_incidente.models import Incidente
from cidades.models import Cidade

class IncidenteForm(forms.ModelForm):
    class Meta:
        model = Incidente
        fields = ('cidade','tipo','data_prevista','gravidade')

cadastro_especialistas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from cadastro_incidente.models import Incidente
from cadastro_abrigos.models import Abrigo
from .forms import IncidenteForm
import smtplib

def is_especialista(user):
	return str(user.groups.first()) == 'Especialistas'

@user_passes_test(is_especialista)
@login_required(login_url='/login/')
def main(request):
	return render(request, 'especialistas/main.html')

@login_required(login_url='/login/')
@user_passes_test(is_especialista)
def cadastro(request):
	if request.method == 'POST':
		def enviar(incidente):
			email = 'tiltaps.hunters@gmail.com'
			senha = 'ricardo_sempre_atento'
			abrigos = Abrigo.objects.filter(cidade=incidente.cidade)
			qtd_abrigos = len(abrigos)
			responsavel = incidente.postado_por
			cidade = incidente.cidade
			destinatario = incidente.cidade.usuario.email
			tipo = incidente.tipo
			gravidade = incidente.gravidade

			mensagem = '''Subject: ALERTA de {}

- Segundo {}, o município de <span style="color:red;"{}</style> será vítima de <span style="color:red;"{}</style> no dia <span style="color:red;"{}</style>, sendo um evento de <span style="color:red;"{}</style>! 
- Há <span style="color:#08c;"{}</style> abrigos nesta área.
- Recomendamos manter a atenção redobrada para qualquer sinal de risco.'''.format(tipo, responsavel, cidade, tipo, data_prevista, gravidade, qtd_abrigos)

			server = smtplib.SMTP('smtp.gmail.com:587')
			
			server.starttls()
			server.ehlo()
			server.login(email, senha)
			server.sendmail(email, [destinatario], mensagem.encode('utf-8'))
			server.quit()

		form = IncidenteForm(request.POST)
		if form.is_valid():
			cidade = form.cleaned_data['cidade']
			tipo = form.cleaned_data['tipo']
			gravidade = form.cleaned_data['gravidade']
			data_prevista = form.cleaned_data['data_prevista']
			postado_por = request.user
			if Incidente.objects.create(cidade=cidade, tipo=tipo, gravidade=gravidade, data_prevista=data_prevista, postado_por=postado_por):
				enviar(Incidente.objects.get(cidade=cidade, tipo=tipo, gravidade=gravidade, data_prevista=data_prevista, postado_por=postado_por))
				return redirect('especialistas:indice')
	else:
		form = IncidenteForm()

	return render(request, 'especialistas/cadastro.html', {'form': form})

@user_passes_test(is_especialista)
@login_required
def indice(request):
	usuario = request.user
	incidentes = Incidente.objects.filter(postado_por=usuario).order_by('-data_prevista')
	return render(request, 'especialistas/seila.html', {'incidentes':incidentes})
	

cadastro_especialistas/templates/especialistas/cadastro.html
<!DOCTYPE html>
<html>
<head>
	<title>Cadastrar Novo Incidente</title>
	<style type="text/css">
		input, select{
			width: 100%;
		}
		.submit{
			width: 100px;
		}
		body {
			font-size: 20px;
			font-family: Arial;
		}
	</style>
</head>
<body>
	<center>
		<form method='POST'>
			{% csrf_token %}
			<table>
			<tr>
				<td>Cidade:</td>
			    <td>{{form.cidade}}</td>
			</tr>
			<tr>
				<td>Tipo:</td>
				<td>{{form.tipo}}</td>
			</tr>
			<tr>
				<td>Data Prevista:</td>
				<td>{{form.data_prevista}}</td>
			</tr>
			<tr>
				<td>Gravidade:</td>
			    <td>{{form.gravidade}}</td>
			</tr>
			<tr>
				<td><input class="submit" type="submit"></td>
			</tr>
			</table>
		</form>
	</center>
</body>
</html>

cadastro_especialistas/templates/especialistas/indice.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<title>Índice de Incidentes</title>
</head>
<body>
	{% for incidente in incidentes %}
		{{ incidente.tipo }}
		{{ incidente.data_prevista }}
		{{ incidente.gravidade }}
		{{ incidente.postado_por }}
		<br>
	{% endfor %}
</body>
</html>

cadastro_especialistas/templates/especialistas/main.html
{% extends "home/index.html" %}
{% block content %}
<center>
<ul>
	<li><a type='button' class='btn btn-success' style="color:#fff;background-color:#000;font-size:30px;" href="{% url 'especialistas:indice' %}">Ver incidentes enviados</a></li><br>
	<li><a type='button' class='btn btn-primary' style="color:#fff;background-color:#000;font-size:30px;" href="{% url 'especialistas:cadastro' %}">Cadastrar Novo Incidente</a></li>
</ul>
</center>
{% endblock content %}

cadastro_especialistas/templates/especialistas/seila.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
{% load static %}
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Natural Guardians</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'home/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'home/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>

<body class="amber accent-2">
  <header class= "navbar-fixed">
  <nav class="grey darken-4">
    <div class="nav-wrapper">
    <div class="row">

    <div class="col l3 left"><a id="logo-container" href="#" class="brand-logo"><span style="padding: 10px 10px 20px 10px; color: #ffd740;">IDesastre</span></a></div>
    <div class="col l5 left"></div>

    <div class="col l2">
        <form>
          <div class="input-field">
            <input id="search" type="search" />
            <label for="search"><i class="material-icons">search</i></label>
          </div>
        </form>
      </div>
    <div class="col l2">
      <ul class="right">
        <li><a href="#"><i class="material-icons left"><span style="color:#ffd740">https</span></i><span style="padding: 10px 10px 20px 10px;color: #ffd740">Área Privada</span></a></li>
      </ul></div>

    </div>
   

    </div>
  </div>
  </nav>
  </header>
    <div class="container amber accent-2">
      <div class="card-panel hoverable">
        <h4>Histórico</h4>
          <table class = "striped bordered">
             <thead>
                <tr>
                   <th>Tipo</th>
                   <th>Gravidade</th>
                   <th>Cidade</th>
                   <th>Data</th>
                </tr>
             </thead>
             
             <tbody>
              {% for incidente in incidentes %}
                <tr>
                   <td>{{incidente.tipo}}</td>
                   <td>{{incidente.gravidade}}</td>
                   <td>{{incidente.cidade}}</td>
                   <td>{{incidente.data_prevista}}</td>
                </tr>
              {% endfor %}
             </tbody>
          </table>
      </div>
    </div>
 
  <footer class="page-footer grey darken-4">
  <div class="container">
   <div class="row">
    <div class="col l8 s12">
      <h5 class="amber-text text-accent-2">Quem somos</h5>
      <p class="grey-text text-lighten-4">A equipe Caçadores de Tiltaps desenvolveu esse website com o intuito de ajudar os agentes governamentais à tatata tututu, pois titititi vavava blublsblubs.</p>
    </div>


<div class="col l4 s12 right">
        <h5 class="amber-text text-accent-2">Equipe Caçadores de Tiltaps</h5>
         <pre><a href="https://www.facebook.com/profile.php?id=100006697067361">Diego Cardoso - Dican</a>
<a href="https://www.facebook.com/eduardo.ribeiro.969300">Eduardo Chedid- Geleia</a>
<a href="https://www.facebook.com/isadbc42">Isadora Bueno- Tranquileba</a>
<a href="https://www.facebook.com/eduardo.borges.58726">Eduardo Borges - Shibiribiu</a>
<a href="https://www.facebook.com/yuriboeira11tx">Yuri Juliano - Derxs</a></pre>
    </div>
   </div>
  </div>
  <div class="footer-copyright black">
   <div class="container center">CHARCODE 2017 - Hackaton - Caçadores de Tíltaps ©</div>
  </div>
 </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="js/materialize.js"></script>
  <script src="js/init.js"></script>

  </body>
</html>